BEGIN;


DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS cooklists;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS users;



CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    pass TEXT NOT NULL,
    joindate DATE DEFAULT now(),
    isadmin BOOLEAN NOT NULL DEFAULT FALSE,
    email TEXT DEFAULT '',
    savedrecipes TEXT DEFAULT '',
    savedcooklists TEXT DEFAULT '',
    buddylist TEXT DEFAULT '',
    received TEXT DEFAULT ''
);

CREATE TABLE recipes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    adddate DATE DEFAULT now(),
    modified TIMESTAMPTZ,
    recipetype TEXT,
    quickdesc TEXT,
    ingredients TEXT NOT NULL,
    directions TEXT NOT NULL,
    addtlnotes TEXT,
    creator INTEGER REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE cooklists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    collaborators TEXT,
    modified TIMESTAMPTZ,
    quickdesc TEXT,
    recipeids TEXT NOT NULL,
    creator INTEGER REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE messages (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sentobject TEXT NOT NULL,
    timesent DATE DEFAULT now(),
    sender INTEGER REFERENCES users(id) ON DELETE SET NULL
);


COMMIT;
